CREATE TABLE Customer (
	cid		BIGINT		PRIMARY KEY AUTO_INCREMENT,
    email	VARCHAR(20)	NOT	NULL,
    passwd	VARCHAR(20)	NOT	NULL,
    
    name	VARCHAR(20)	NOT	NULL,
    ssn		VARCHAR(14)	NOT	NULL,	-- 800125-1234567
    phone	VARCHAR(13)	NOT	NULL,	-- 010-6633-2285
    regDate	TIMESTAMP	NOT	NULL	DEFAULT	CURRENT_TIMESTAMP
)AUTO_INCREMENT = 1001;

SELECT * FROM Customer;

CREATE TABLE Account (
	aid				BIGINT		PRIMARY KEY	AUTO_INCREMENT,
	accountNum		VARCHAR(9) 	NOT	NULL,					-- ####-####
	balance			DOUBLE		NOT NULL	DEFAULT 0.0,
	interestRate	DOUBLE		NOT NULL	DEFAULT 0.0,
	overdraft		DOUBLE		NOT NULL	DEFAULT 0.0,
	accountType		CHAR(1)		NOT NULL	DEFAULT 'S',
	customerId		BIGINT		NOT	NULL,
	regDate			TIMESTAMP	NOT NULL	DEFAULT	CURRENT_TIMESTAMP,
	
	CONSTRAINT Account_customerId_FK FOREIGN KEY (customerId) REFERENCES Customer(cid)
)AUTO_INCREMENT = 3001;

SELECT * FROM Account;